-- MySQL Script generated by MySQL Workbench
-- Sun Mar  2 03:08:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cucimobil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cucimobil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cucimobil` DEFAULT CHARACTER SET utf8 ;
USE `db_cucimobil` ;

-- -----------------------------------------------------
-- Table `db_cucimobil`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cucimobil`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `insert_by` INT NULL,
  `update_by` INT NULL,
  `delete_by` INT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL,
  `delete_at` DATETIME NULL,
  `is_delete` TINYINT NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cucimobil`.`pelanggan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cucimobil`.`pelanggan` (
  `id_pelanggan` CHAR(13) NOT NULL,
  `nama_pelanggan` VARCHAR(45) NOT NULL,
  `telepon` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `insert_by` INT NULL,
  `update_by` INT NULL,
  `delete_by` INT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL,
  `delete_at` DATETIME NULL,
  `is_delete` TINYINT NOT NULL,
  PRIMARY KEY (`id_pelanggan`),
  INDEX `users_1_idx` (`insert_by` ASC) VISIBLE,
  INDEX `users_2_idx` (`update_by` ASC) VISIBLE,
  INDEX `users_3_idx` (`delete_by` ASC) VISIBLE,
  CONSTRAINT `pelanggan_1`
    FOREIGN KEY (`insert_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pelanggan_2`
    FOREIGN KEY (`update_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pelanggan_3`
    FOREIGN KEY (`delete_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cucimobil`.`karyawan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cucimobil`.`karyawan` (
  `id_karyawan` INT NOT NULL AUTO_INCREMENT,
  `nama_karyawan` VARCHAR(45) NOT NULL,
  `telepon` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `insert_by` INT NULL,
  `update_by` INT NULL,
  `delete_by` INT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL,
  `delete_at` DATETIME NULL,
  `is_delete` TINYINT NOT NULL,
  PRIMARY KEY (`id_karyawan`),
  INDEX `karyawan_1_idx` (`insert_by` ASC) VISIBLE,
  INDEX `karyawan_2_idx` (`update_by` ASC) VISIBLE,
  INDEX `karyawan_3_idx` (`delete_by` ASC) VISIBLE,
  CONSTRAINT `karyawan_1`
    FOREIGN KEY (`insert_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `karyawan_2`
    FOREIGN KEY (`update_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `karyawan_3`
    FOREIGN KEY (`delete_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cucimobil`.`layanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cucimobil`.`layanan` (
  `id_layanan` INT NOT NULL AUTO_INCREMENT,
  `nama_layanan` VARCHAR(45) NOT NULL,
  `harga` DECIMAL(15,2) NOT NULL,
  `jenis_layanan` VARCHAR(45) NOT NULL,
  `insert_by` INT NULL,
  `update_by` INT NULL,
  `delete_by` INT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL,
  `delete_at` DATETIME NULL,
  `is_delete` TINYINT NOT NULL,
  PRIMARY KEY (`id_layanan`),
  INDEX `layanan_1_idx` (`insert_by` ASC) VISIBLE,
  INDEX `layanan_2_idx` (`update_by` ASC) VISIBLE,
  INDEX `layanan_3_idx` (`delete_by` ASC) VISIBLE,
  CONSTRAINT `layanan_1`
    FOREIGN KEY (`insert_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `layanan_2`
    FOREIGN KEY (`update_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `layanan_3`
    FOREIGN KEY (`delete_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cucimobil`.`pesanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cucimobil`.`pesanan` (
  `id_pesanan` CHAR(8) NOT NULL,
  `tanggal_pesanan` DATE NOT NULL,
  `merk_mobil` VARCHAR(45) NOT NULL,
  `nomor_plat` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `insert_by` INT NULL,
  `update_by` INT NULL,
  `delete_by` INT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL,
  `delete_at` DATETIME NULL,
  `is_delete` TINYINT NOT NULL,
  `id_pelanggan` CHAR(13) NOT NULL,
  `id_layanan` INT NOT NULL,
  PRIMARY KEY (`id_pesanan`),
  INDEX `pesanan_1_idx` (`insert_by` ASC) VISIBLE,
  INDEX `pesanan_2_idx` (`update_by` ASC) VISIBLE,
  INDEX `pesanan_3_idx` (`delete_by` ASC) VISIBLE,
  INDEX `pesanan_4_idx` (`id_pelanggan` ASC) VISIBLE,
  INDEX `pesanan_5_idx` (`id_layanan` ASC) VISIBLE,
  CONSTRAINT `pesanan_1`
    FOREIGN KEY (`insert_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pesanan_2`
    FOREIGN KEY (`update_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pesanan_3`
    FOREIGN KEY (`delete_by`)
    REFERENCES `db_cucimobil`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pesanan_4`
    FOREIGN KEY (`id_pelanggan`)
    REFERENCES `db_cucimobil`.`pelanggan` (`id_pelanggan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pesanan_5`
    FOREIGN KEY (`id_layanan`)
    REFERENCES `db_cucimobil`.`layanan` (`id_layanan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
